spring:
  application: eureka-copy
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名为peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/  # 将自己注册到peer2 上面
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2 # 指定当profile=peer1时，主机名为peer1
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/  # 将自己注册到peer2 上面
